server:
  port: ${SERVER_PORT:0}

collector:
  kafka:
    producer:
      properties:
        bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.yandex.practicum.telemetry.serialization.avro.GeneralAvroSerializer
      topics:
        sensors-events: telemetry.sensors.v1
        hubs-events: telemetry.hubs.v1

grpc:
  server:
    port: 59091

logging:
  level:
    ru.yandex.practicum.telemetry: DEBUG